### PR TITLE
bug: use correct code

### PR DESCRIPTION
**Pull request by MylesBorins**
Currently you are testing for

**Up, Down, Up, Down, Left, Right, B, A**

The Konami Code is

**Up, Up, Down, Down, Left, Right, Left, Right, B, A**

### CODE REVIEW

**Comment by sintaxi** [comment]
oh dear, merge this immediately!

**Comment by JonAbrams** [comment]
!!!!

> You had one job

**Comment by augbog** [comment]
... I am a disgrace to the human race... Thanks for catching that.

**Comment by MylesBorins** [comment]
Nawww  this module is great!

**Pull request merged**
